# Official docker image.
image: docker:dind

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_USER: "username"
  CI_REGISTRY_PASSWORD: "password"
  CI_REGISTRY: "localhost:5000"
  API_IMAGE: "notary/api"
  DASHBOARD_IMAGE: "notary/dashboard"

  RANCHER_COMPOSE_DOWNLOAD: "http://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz"
  RANCHER_COMPOSE_TAR: "rancher-compose-linux-amd64-v0.12.5.tar.gz"
  RANCHER_COMPOSE_DIR: "rancher-compose-v0.12.5"
  STACK_NAME: "notary-cluster"

  RANCHER_ACCESS_KEY: "707C612461CC3ED6094D"
  RANCHER_SECRET_KEY: "NiHfenzmuAzQo7P8QdBiKgWLZPzJHJDUrMQqy1th"
  RANCHER_URL: "http://217.172.12.189:8080/v1/projects/1a19"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - test
  - build
  - publish
  - deploy

build:
  stage: build
  script:
    - docker build --pull -f Dockerfile.api -t "$CI_REGISTRY"/"$API_IMAGE" api
    - docker build --pull -f Dockerfile.dashboard -t "$CI_REGISTRY"/"$DASHBOARD_IMAGE" dashboard

publish:
  stage: publish
  script:
    - docker push "$CI_REGISTRY"/"$API_IMAGE"
    - docker push "$CI_REGISTRY"/"$DASHBOARD_IMAGE"

deploy:
  stage: deploy
  script:
    - wget $RANCHER_COMPOSE_DOWNLOAD #insecure, use https instead
    - tar -zxvf $RANCHER_COMPOSE_TAR
    - ls -l ./$RANCHER_COMPOSE_DIR/
    - alias rancher-compose=$PWD/$RANCHER_COMPOSE_DIR/rancher-compose

    - rancher-compose --debug -p $STACK_NAME --url $RANCHER_URL --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY -f docker-compose.yml up --force-upgrade --pull -d
    - rancher-compose --debug -p $STACK_NAME --url $RANCHER_URL --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY -f docker-compose.yml up --confirm-upgrade -d
  environment: "Default"
  only:
    - master

