FROM node:13.5.0-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY package*.json ./

RUN npm config set registry http://registry.npmjs.org/

USER node
RUN npm install --production --loglevel verbose
COPY --chown=node:node . .

EXPOSE 3000

CMD [ "npm", "start" ]