FROM node:slim
ENV NPM_CONFIG_LOGLEVEL warn
ENV NPM_CONFIG_REGISTRY "http://registry.npmjs.org"

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY package*.json ./

USER node
RUN npm install
COPY --chown=node:node . .

RUN mkdir uploads

EXPOSE 3000

ENV NODE_ENV production
CMD [ "node", "server.js" ]