version: "2"

services:
  dashboard:
    image: localhost:5000/notary/dashboard
    container_name: dashboard
    hostname: dashboard
    ports:
      - "80:80"
    environment:
      - "VUE_APP_API=localhost"
    depends_on:
      - api
  api:
    image: localhost:5000/notary/api
    container_name: api
    hostname: api
    environment:
      - "DB_HOST=mongo"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - "mongo:/data/db"

volumes: 
  mongo: