version: "2"

services:
  dashboard:
    image: notary/dashboard
    hostname: dashboard
    ports:
      - "80:80"
    environment:
      - "VUE_APP_API=localhost"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    image: notary/api
    hostname: api
    environment:
      - "DB_HOST=mongo"
    depends_on:
      - mongo
  mongo:
    image: mongo
    hostname: mongo
